name: Java CI & Release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Compile
        run: |
          mkdir -p bin
          find src -name "*.java" > sources.txt
          javac -d bin -cp "lib/*" @sources.txt

      - name: Create JAR
        run: |
          jar cfe Biblioteca.jar application.Main -C bin .

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Biblioteca-jar
          path: Biblioteca.jar

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: Biblioteca.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
